'use strict';
(() => {
 const qs=window.QUIZ_DATA.questions,KEY='gif-break-review-v1', $=id=>document.getElementById(id);let approvals={},checks={},running=false;
 try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved==='object'&&!Array.isArray(saved))approvals=Object.fromEntries(qs.filter(q=>saved[q.id]&&typeof saved[q.id]==='object'&&typeof saved[q.id].approved==='boolean').map(q=>[q.id,saved[q.id]]));}catch{}
 const previewVersions={},boxes={};
 function identity(q){return JSON.stringify([q.mediaUrl,window.LOCAL_MEDIA?.[q.id]?.sha256||window.LOCAL_MEDIA?.[q.id]?.path||null]);}
 function approved(q){return Boolean(approvals[q.id]?.approved&&approvals[q.id]?.identity===identity(q));}
 function paths(q){return [...new Set([window.LOCAL_MEDIA?.[q.id]?.path,q.mediaUrl].filter(Boolean))];}
 function summary(){const n=qs.filter(approved).length;$('reviewSummary').textContent=`${n} / ${qs.length} visually approved`;try{localStorage.setItem(KEY,JSON.stringify(approvals));}catch{$('reviewStorageStatus').textContent='Review storage is unavailable. Export the review record before closing this page.';}}
 async function probe(url){return new Promise(resolve=>{const img=new Image();img.referrerPolicy='no-referrer';let done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timeout);img.onload=null;img.onerror=null;resolve(value);};const timeout=setTimeout(()=>{finish({ok:false,error:'Timed out'});img.removeAttribute('src');},18000);img.onload=()=>finish({ok:true,width:img.naturalWidth,height:img.naturalHeight,url});img.onerror=()=>finish({ok:false,error:'Could not load'});img.src=url;});}
 async function check(q,preview=false){const version=preview?(previewVersions[q.id]??0)+1:null;if(preview)previewVersions[q.id]=version;const status=$('status-'+q.id);status.textContent='Loading…';let result={ok:false,error:'No usable media'};for(const url of paths(q)){result=await probe(url);if(result.ok)break;}checks[q.id]={...result,checkedAt:new Date().toISOString()};status.textContent=result.ok?`Image loads: ${result.width} × ${result.height}. Animation and content still need visual review.`:'LOAD FAILED — open the source privately and replace or download a working version.';
  if(preview&&result.ok&&previewVersions[q.id]===version){const holder=$('preview-'+q.id);holder.replaceChildren();const img=document.createElement('img');img.alt=`Host preview: ${q.answer}`;img.referrerPolicy='no-referrer';img.onload=()=>{if(previewVersions[q.id]===version)boxes[q.id].disabled=false;};img.src=result.url;holder.append(img);holder.hidden=false;}
  return result;
 }
 qs.forEach(q=>{const card=document.createElement('article');card.className='review-item';const title=document.createElement('h2');title.textContent=`${q.id.slice(1)} / ${q.answer}`;const scene=document.createElement('p');scene.className='small';scene.textContent=q.scene;const note=document.createElement('p');note.className='review-note';note.textContent=q.reviewNote||'Watch the full loop; verify the source, captions and workplace suitability.';
  const links=document.createElement('div');links.className='media-links';[['Source page',q.sourceUrl],['Direct GIF',q.mediaUrl]].forEach(([text,url])=>{const a=document.createElement('a');a.textContent=text+' ↗';a.href=url;a.target='_blank';a.rel='noopener noreferrer';links.append(a);});
  const status=document.createElement('p');status.id='status-'+q.id;status.className='status';status.textContent=`Not checked here. URL method: ${q.mediaUrlMethod}.`;
  const preview=document.createElement('div');preview.className='review-image';preview.id='preview-'+q.id;preview.hidden=true;
  const actions=document.createElement('div');actions.className='actions';const show=document.createElement('button');show.textContent='Load / preview';show.onclick=()=>check(q,true);const hide=document.createElement('button');hide.textContent='Hide motion';hide.onclick=()=>{previewVersions[q.id]=(previewVersions[q.id]??0)+1;preview.replaceChildren();preview.hidden=true;};actions.append(show,hide);
  const label=document.createElement('label'),box=document.createElement('input'),text=document.createElement('span');boxes[q.id]=box;box.type='checkbox';box.checked=approved(q);box.disabled=!box.checked;box.onchange=()=>{approvals[q.id]={approved:box.checked,mediaUrl:q.mediaUrl,identity:identity(q),reviewedAt:new Date().toISOString()};summary();};text.textContent='After loading a preview, watch the complete loop before checking: correct source, no answer-revealing text, suitable audience, acceptable motion and quality.';label.append(box,text);card.append(title,scene,note,links,status,preview,actions,label);$('reviewList').append(card);
 });
 $('checkAll').onclick=async()=>{if(running)return;running=true;$('checkAll').disabled=true;let next=0,completed=0;async function worker(){while(next<qs.length){const q=qs[next++];await check(q);completed++;$('checkProgress').textContent=`Checked ${completed} / ${qs.length}. ${Object.values(checks).filter(x=>x.ok).length} currently load. This is not a visual approval.`;}}await Promise.all(Array.from({length:4},worker));running=false;$('checkAll').disabled=false;};
 $('hideAll').onclick=()=>{qs.forEach(q=>{previewVersions[q.id]=(previewVersions[q.id]??0)+1;const x=$('preview-'+q.id);x.replaceChildren();x.hidden=true;});};
 $('exportReview').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),approvals,checks},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gif-break-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};summary();
})();
