/* HTTP/nested-path tests with synthetic media. Real media has a separate report. */
'use strict';
const {chromium}=require('playwright'),{expect}=require('playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=path.resolve(__dirname,'..'),DATA=JSON.parse(fs.readFileSync(path.join(ROOT,'data/questions.json'))),KEY='gif-break-state-v1',TOTAL=DATA.questions.length;
const GIF=Buffer.concat([Buffer.from('47494638396102000200800000000000ffffff','hex'),...Array(2).fill(Buffer.from('21f904000a0000002c000000000200020000020344020500','hex')),Buffer.from('3b','hex')]);
const results=[],requests=[],errors=[];
const server=http.createServer((req,res)=>{
 requests.push(req.url);const url=new URL(req.url,'http://localhost');let name=decodeURIComponent(url.pathname).replace(/^\/repository-name\//,'/');
 if(name.endsWith('/'))name+='index.html';const file=path.resolve(ROOT,'.'+name);
 if(!file.startsWith(ROOT+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(file,(error,body)=>{if(error){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.gif':'image/gif'})[path.extname(file)]||'application/octet-stream');res.end(body);});
});
const record=text=>{results.push(text);console.log('PASS:',text);};
let browser;
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`,base=origin+'/repository-name/';
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 async function context(options={}){const c=await browser.newContext({viewport:{width:1600,height:900},...options});await c.route('https://**/*',route=>route.request().resourceType()==='image'?route.fulfill({status:200,contentType:'image/gif',body:GIF}):route.abort());c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));return c;}
 const c=await context(),p=await c.newPage();await p.goto(base);await expect(p.locator('.round-card')).toHaveCount(DATA.rounds.length);await expect(p.locator('#resumeBtn')).toBeHidden();await p.screenshot({path:path.join(ROOT,'evidence/setup-desktop.png'),fullPage:true});
 await p.locator('#teamNames').fill('Only one');await p.locator('#startBtn').click();await expect(p.locator('#setupError')).toContainText('between 2 and 8');
 await p.locator('#teamNames').fill('Same\nsame');await p.locator('#startBtn').click();await expect(p.locator('#setupError')).toContainText('different name');
 await p.locator('#teamNames').fill('<img src=x onerror=alert(1)>\nTeam B\nTeam C');await p.locator('#startBtn').click();await expect(p.locator('#clip')).toBeVisible();
 await expect(p.locator('#timerValue')).toHaveText('45');await p.waitForTimeout(1200);await expect(p.locator('#timerValue')).toHaveText('45');await p.setViewportSize({width:1366,height:768});await p.screenshot({path:path.join(ROOT,'evidence/game-desktop.png'),fullPage:true});const nextRect=await p.locator('#nextBtn').boundingBox();assert(nextRect.y+nextRect.height<=768,'Primary controls must fit a 1366x768 projector view');await p.setViewportSize({width:1600,height:900});
 assert.equal(await p.locator('#answerText').textContent(),'');assert.equal(await p.locator('#sourceLink').getAttribute('href'),null);assert.equal(await p.locator('#clip').getAttribute('alt'),'Mystery clip 1');
 record('Setup validates team count/unique names; media readiness never automatically starts time; pre-reveal text and alt text contain no answer.');
 await p.locator('#timerBtn').click();await p.waitForTimeout(1200);await p.locator('#timerBtn').click();const paused=await p.locator('#timerValue').textContent();assert(+paused<45);await p.waitForTimeout(500);assert.equal(await p.locator('#timerValue').textContent(),paused);await p.locator('body').click({position:{x:1,y:1}});await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#timerValue').textContent(),paused);
 await p.locator('#timerBtn').click();await p.waitForTimeout(300);await p.locator('#motionBtn').click();await expect(p.locator('#clip')).toBeHidden();await expect(p.locator('#timerBtn')).toBeDisabled();const hidden=await p.locator('#timerValue').textContent();await p.waitForTimeout(1100);assert.equal(await p.locator('#timerValue').textContent(),hidden);await p.locator('#motionBtn').click();await expect(p.locator('#clip')).toBeVisible();await expect(p.locator('#timerBtn')).toHaveText('Start timer');
 // Test the visibility event deterministically; the OS/venue tab switch remains a host check.
 await p.locator('#timerBtn').click();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await expect(p.locator('#timerBtn')).toHaveText('Start timer');await p.evaluate(()=>delete document.hidden);
 await p.locator('#hintBtn').click();await expect(p.locator('#hintText')).toHaveText(DATA.questions[0].hint);await p.locator('#revealBtn').click();await expect(p.locator('#answerText')).toHaveText('The Matrix');await expect(p.locator('#timerBtn')).toBeDisabled();
 const award=p.locator('#awardButtons button');await expect(award).toHaveCount(3);assert.equal(await award.first().textContent(),'<img src=x onerror=alert(1)>');assert.equal(await p.locator('#awardButtons img').count(),0);
 await award.nth(0).click();await expect(award.nth(0)).toHaveAttribute('aria-pressed','true');await award.nth(0).click();await expect(award.nth(0)).toHaveAttribute('aria-pressed','false');await award.nth(0).click();await award.nth(1).click();
 await p.locator('#nextBtn').click();await p.locator('#prevBtn').click();await expect(award.nth(0)).toHaveAttribute('aria-pressed','true');await expect(p.locator('#hintText')).not.toBeEmpty();
 p.once('dialog',d=>d.accept());await p.locator('#voidBtn').click();await expect(award.nth(0)).toBeDisabled();await p.locator('#scoresBtn').click();await expect(p.locator('#scoreList')).toContainText(`0 / ${TOTAL-1}`);await p.locator('#closeScoresBtn').click();await p.locator('#voidBtn').click();await p.locator('#scoresBtn').click();await expect(p.locator('#scoreList')).toContainText(`1 / ${TOTAL}`);await p.locator('#closeScoresBtn').click();
 await p.reload();await p.locator('#resumeBtn').click();await expect(p.locator('#answerText')).toHaveText('The Matrix');await expect(award.nth(1)).toHaveAttribute('aria-pressed','true');
 record('Timer start/pause/resume, hidden motion, tab-visibility event, reveal stop, hint, safe team-name rendering, reversible awards, revisits, void/restore and real localStorage resume pass.');
 for(let i=1;i<TOTAL;i++){
  await p.locator('#nextBtn').click();await expect(p.locator('#clip')).toBeVisible();await expect(p.locator('#roundLabel')).toContainText(`${i+1} of ${TOTAL}`);await expect(p.locator('#answerPanel')).toBeHidden();assert.equal(await p.locator('#sourceLink').getAttribute('href'),null);assert.equal(await p.locator('#clip').getAttribute('alt'),`Mystery clip ${i+1}`);
  if(i===29){await expect(p.locator('#questionType')).toHaveText('VIDEO-GAME WILDCARD');p.once('dialog',d=>d.accept());await p.locator('#voidBtn').click();await expect(p.locator('#timerBtn')).toBeDisabled();await p.locator('#nextBtn').click();await p.locator('#prevBtn').click();await expect(p.locator('#questionType')).toContainText('VOID');await p.locator('#voidBtn').click();await expect(p.locator('#questionType')).toHaveText('VIDEO-GAME WILDCARD');}
  if(DATA.questions[i].kind==='TV series')await expect(p.locator('#questionLabel')).toHaveText('Which TV series is this?');await p.locator('#revealBtn').click();await expect(p.locator('#answerText')).toHaveText(DATA.questions[i].answer);await expect(p.locator('#sourceLink')).toHaveAttribute('href',DATA.questions[i].sourceUrl);
  const aliases=DATA.questions[i].acceptedAnswers.slice(1);assert.equal(await p.locator('#acceptedText').textContent(),aliases.length?'Also accept: '+aliases.join(' · '):'');
 }
 await p.locator('#nextBtn').click();await expect(p.locator('#finish')).toBeVisible();const rows=await p.locator('#finalScores .score-row').allTextContents();assert(rows[0].startsWith('1. ')&&rows[1].startsWith('1. ')&&rows[2].startsWith('3. '));
 const download=await Promise.all([p.waitForEvent('download'),p.locator('#exportBtn').click()]);const exported=JSON.parse(fs.readFileSync(await download[0].path()));assert.equal(exported.scores[0].points,1);assert.equal(exported.scores[1].points,1);assert.equal(exported.game.teams.length,3);
 record('All '+TOTAL+' navigation positions, reveals, exact alias lists (including Nemo/Dory, Wednesday and Mandalorian), wildcard void/revisit, tied final ranking and score export pass.');
 assert(!requests.some(u=>u.includes('assets/gifs/')));record('Relative assets work at /repository-name/; no requests for nonexistent local GIFs when the map is empty.');
 const mobile=await context({viewport:{width:390,height:844},reducedMotion:'reduce'}),mp=await mobile.newPage();await mp.goto(base);assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:path.join(ROOT,'evidence/setup-mobile.png'),fullPage:true});await mp.locator('#startBtn').click();await expect(mp.locator('#clip')).toBeHidden();await expect(mp.locator('#timerBtn')).toBeDisabled();await mp.locator('#motionBtn').click();await expect(mp.locator('#clip')).toBeVisible();assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:path.join(ROOT,'evidence/game-mobile.png'),fullPage:true});
 await mp.locator('#hintBtn').focus();await mp.keyboard.press('Space');await expect(mp.locator('#hintText')).not.toBeEmpty();await expect(mp.locator('#timerBtn')).toHaveText('Start timer');await mp.locator('body').click({position:{x:1,y:1}});await mp.keyboard.press('r');await expect(mp.locator('#answerPanel')).toBeVisible();
 record('390 px setup/game layouts, reduced-motion opt-in, native focused-button Space and reveal shortcut pass.');
 const saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
 const legacy=await context();await legacy.addInitScript(([k,s])=>{if(location.protocol==='http:'&&!localStorage.getItem(k))localStorage.setItem(k,JSON.stringify(s));},[KEY,{version:1,teams:['Legacy A','Legacy B'],index:39,seconds:45,remaining:30,voids:[],awards:{q01:{0:true},q40:{0:true}},revealed:{q40:true},hints:{}}]);const lp=await legacy.newPage();await lp.goto(base);await lp.locator('#resumeBtn').click();await expect(lp.locator('#answerText')).toHaveText(DATA.questions[39].answer);await lp.locator('#nextBtn').click();await expect(lp.locator('#roundLabel')).toContainText(`41 of ${TOTAL}`);await expect(lp.locator('#answerPanel')).toBeHidden();await lp.locator('#scoresBtn').click();await expect(lp.locator('#scoreList')).toContainText(`2 / ${TOTAL}`);await legacy.close();
 const last=await context();await last.addInitScript(([k,s])=>{if(location.protocol==='http:'&&!localStorage.getItem(k))localStorage.setItem(k,JSON.stringify(s));},[KEY,{version:1,teams:['Last A','Last B'],index:TOTAL-1,seconds:45,remaining:45,voids:[],awards:{q41:{0:true}},revealed:{},hints:{}}]);const lastp=await last.newPage();await lastp.goto(base);await lastp.locator('#resumeBtn').click();await expect(lastp.locator('#clip')).toBeVisible();await expect(lastp.locator('#questionLabel')).toHaveText('Which TV series is this?');await lastp.locator('#revealBtn').click();await lastp.locator('#awardButtons button').first().click();lastp.once('dialog',d=>d.accept());await lastp.locator('#voidBtn').click();await lastp.locator('#scoresBtn').click();await expect(lastp.locator('#scoreList')).toContainText(`1 / ${TOTAL-1}`);await lastp.locator('#closeScoresBtn').click();await lastp.locator('#voidBtn').click();await lastp.locator('#prevBtn').click();await lastp.locator('#nextBtn').click();await expect(lastp.locator('#awardButtons button').first()).toHaveAttribute('aria-pressed','true');await lastp.reload();await lastp.locator('#resumeBtn').click();await expect(lastp.locator('#answerText')).toHaveText(DATA.questions[TOTAL-1].answer);await lastp.locator('#nextBtn').click();await expect(lastp.locator('#finalScores')).toContainText(`2 / ${TOTAL}`);await last.close();record('An existing 40-question saved game keeps its awards and continues into q41; q100 TV prompting, scoring, void/restore, revisit, resume and final totals pass.');
 for(const invalid of ['{broken',JSON.stringify({...saved,teams:[null,'B']}),JSON.stringify({...saved,teams:Array(9).fill('A')}),JSON.stringify({...saved,seconds:'oops'}),JSON.stringify({...saved,remaining:null}),JSON.stringify({...saved,voids:['q999']}),JSON.stringify({...saved,awards:{q999:{0:true}}}),JSON.stringify({...saved,revealed:['q01']}),JSON.stringify({...saved,hints:42})]){
  const ic=await context();await ic.addInitScript(([k,v])=>{if(location.protocol==='http:')localStorage.setItem(k,v);},[KEY,invalid]);const ip=await ic.newPage();await ip.goto(base);await expect(ip.locator('#resumeBtn')).toBeHidden();await ic.close();
 }
 const blocked=await context();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage denied');}});});const bp=await blocked.newPage();await bp.goto(base);await bp.locator('#startBtn').click();await expect(bp.locator('#clip')).toBeVisible();await expect(bp.locator('#liveNotice')).toContainText('storage is unavailable');await bp.goto(base+'review.html');await expect(bp.locator('#reviewStorageStatus')).toContainText('unavailable');
 record('Malformed saved JSON/state and denied browser storage are handled without crashes.');
 const clocked=await context(),tp=await clocked.newPage();await tp.clock.install();await tp.goto(base);await tp.locator('#startBtn').click();await expect(tp.locator('#clip')).toBeVisible();await tp.locator('#timerBtn').click();await tp.clock.runFor(45001);await expect(tp.locator('#timerValue')).toHaveText('0');await expect(tp.locator('#timerStatus')).toHaveText('Pens down');await expect(tp.locator('#answerPanel')).toBeHidden();await expect(tp.locator('#roundLabel')).toContainText(`1 of ${TOTAL}`);await tp.locator('#timerBtn').click();await expect(tp.locator('#timerValue')).toHaveText('45');record('Expiry stops at zero without reveal/navigation; explicit timer reset works.');
 await tp.locator('body').click({position:{x:1,y:1}});await tp.keyboard.press('Space');await expect(tp.locator('#timerBtn')).toHaveText('Start timer');await tp.keyboard.press('h');await expect(tp.locator('#hintText')).not.toBeEmpty();await tp.keyboard.press('m');await expect(tp.locator('#clip')).toBeHidden();await tp.keyboard.press('m');await expect(tp.locator('#clip')).toBeVisible();await tp.keyboard.press('ArrowRight');await expect(tp.locator('#roundLabel')).toContainText(`2 of ${TOTAL}`);await tp.keyboard.press('ArrowLeft');await expect(tp.locator('#roundLabel')).toContainText(`1 of ${TOTAL}`);
 await tp.evaluate(()=>{const input=document.createElement('input');input.id='typingTest';document.querySelector('#game').append(input);input.focus();});await tp.keyboard.type('rhm ');await expect(tp.locator('#answerPanel')).toBeHidden();await expect(tp.locator('#typingTest')).toHaveValue('rhm ');await tp.locator('#typingTest').evaluate(el=>el.remove());
 await tp.locator('#fullscreenBtn').click();assert(await tp.evaluate(()=>Boolean(document.fullscreenElement)));await tp.locator('#fullscreenBtn').click();assert(await tp.evaluate(()=>!document.fullscreenElement));await tp.evaluate(()=>{document.documentElement.requestFullscreen=()=>Promise.reject(new Error('Denied'));});await tp.locator('#fullscreenBtn').click();await expect(tp.locator('#fullscreenBtn')).toHaveText('Use browser full screen');record('All keyboard shortcuts, non-intercepted typing, full-screen entry/exit and denied full-screen permission pass.');
 const fallback=await context();await fallback.route('**/data/local-media.js',r=>r.fulfill({contentType:'text/javascript',body:'window.LOCAL_MEDIA={q01:{path:"assets/gifs/q01.gif"}};'}));const fb=await fallback.newPage();await fb.goto(base);await fb.locator('#startBtn').click();await expect(fb.locator('#clip')).toBeVisible();await expect(fb.locator('#clip')).toHaveAttribute('src',DATA.questions[0].mediaUrl);record('A missing mapped local file falls back to its remote GIF at the nested path.');
 const failing=await context();await failing.unroute('https://**/*');await failing.route('https://**/*',r=>r.abort());const fp=await failing.newPage();await fp.goto(base);await fp.locator('#startBtn').click();await expect(fp.locator('#mediaStatus')).toContainText('could not load');await expect(fp.locator('#timerBtn')).toBeDisabled();
 const stalled=await context();let pending=[];await stalled.unroute('https://**/*');await stalled.route('https://**/*',r=>{pending.push(r);});const sp=await stalled.newPage();await sp.clock.install();await sp.goto(base);await sp.locator('#startBtn').click();await expect(sp.locator('#timerBtn')).toBeDisabled();await sp.clock.runFor(18001);await expect(sp.locator('#mediaStatus')).toContainText('could not load');await expect(sp.locator('#timerValue')).toHaveText('45');await stalled.close();record('Failed requests and an 18-second timeout display errors and cannot consume thinking time.');
 const review=await context(),rp=await review.newPage();await rp.goto(base+'review.html');await expect(rp.locator('.review-item')).toHaveCount(TOTAL);await expect(rp.locator('.review-item input').first()).toBeDisabled();await rp.locator('#checkAll').click();await expect(rp.locator('#checkProgress')).toContainText(`Checked ${TOTAL} / ${TOTAL}`);await expect(rp.locator('#reviewSummary')).toHaveText(`0 / ${TOTAL} visually approved`);await expect(rp.locator('.review-item input').first()).toBeDisabled();await rp.locator('.review-item').first().getByRole('button',{name:'Load / preview'}).click();await expect(rp.locator('.review-item input').first()).toBeEnabled();await rp.locator('.review-item input').first().check();await expect(rp.locator('#reviewSummary')).toHaveText(`1 / ${TOTAL} visually approved`);
 const reviewDownload=await Promise.all([rp.waitForEvent('download'),rp.locator('#exportReview').click()]);const reviewRecord=JSON.parse(fs.readFileSync(await reviewDownload[0].path()));assert.equal(reviewRecord.checks.q01.ok,true);assert.equal(reviewRecord.approvals.q01.approved,true);
 await rp.reload();await expect(rp.locator('#reviewSummary')).toHaveText(`1 / ${TOTAL} visually approved`);await review.route('**/data/local-media.js',r=>r.fulfill({contentType:'text/javascript',body:'window.LOCAL_MEDIA={q01:{path:"assets/gifs/q01.gif",sha256:"changed"}};'}));await rp.reload();await expect(rp.locator('#reviewSummary')).toHaveText(`0 / ${TOTAL} visually approved`);
 await rp.evaluate(()=>localStorage.setItem('gif-break-review-v1','42'));await rp.reload();await expect(rp.locator('.review-item')).toHaveCount(TOTAL);record('Limited-concurrency preflight does not grant approvals; preview opt-in, saved approvals, changed-media invalidation, corrupt review storage and review export pass.');
 const rootPage=await c.newPage();await rootPage.goto(origin+'/');await expect(rootPage.locator('.round-card')).toHaveCount(DATA.rounds.length);const sheet=await c.newPage();await sheet.goto(base+'answer-sheet.html');assert.equal(await sheet.locator('td:first-child').count(),TOTAL);await expect(sheet.locator('.print-page')).toHaveCount(Math.ceil(TOTAL/40));for(const q of DATA.questions)assert(!(await sheet.locator('body').innerText()).includes(q.answer));record('Domain-root setup and answer-free printable sheet pass.');
 assert.deepEqual(errors,[]);record('No JavaScript page errors.');
 fs.writeFileSync(path.join(ROOT,'evidence/ui-test-results.json'),JSON.stringify({checkedAt:new Date().toISOString(),questionCount:TOTAL,mode:'real-http-nested-path-synthetic-media',syntheticMedia:true,syntheticStorage:false,realMediaValidated:false,passed:results},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));});
