#!/usr/bin/env python3
"""Validate the canonical JSON and regenerate the browser data and host key."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT/'data/questions.json').read_text())
qs=data['questions']
assert len(qs)==40, 'Exactly 40 questions required'
assert [q['id'] for q in qs]==[f'q{i:02}' for i in range(1,41)], 'IDs/order must be q01–q40'
for q in qs:
    assert q['answer'] in q['acceptedAnswers']
    assert q['round'] == (int(q['id'][1:])-1)//10+1
    assert q['mediaUrl'].startswith('https://') and q['sourceUrl'].startswith('https://')
    assert q['localPath']==f"assets/gifs/{q['id']}.gif"
(ROOT/'data/questions.js').write_text('// Generated from questions.json. Do not edit this file by hand.\nwindow.QUIZ_DATA = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n')
lines=['# The GIF Break — host answer key','', '**Spoilers. Keep this off the audience display.**', '',
'Prepared 6 October 2026; media validation updated in this project. The 40 remote animations were fetched for private inspection, decoded and screened across their full frame sequences. Eight selections were improved. No third-party GIFs are bundled for redistribution. See evidence/VALIDATION.md and the dated media reports for exact results and remaining venue checks; host approvals are recorded separately in review.html.', '',
'One point per correct source. Accept the aliases below and equivalent localized titles. No extra points for a year, actor or precise sequel. For broad franchise entries, do not demand a sequel title that the source metadata does not establish. For the TV round, require the series rather than just the character.', '']
for r in data['rounds']:
    lines += [f"## Round {r['id']} — {r['title']}", '', '| # | Answer | Scene / recognition cue |', '|---|---|---|']
    for q in qs:
        if q['round']==r['id']: lines.append(f"| {int(q['id'][1:])} | {q['answer']} | {q['scene']} |")
    lines.append('')
lines += ['## Full media and acceptance details','']
for q in qs:
    lines += [f"### {q['id'][1:]} — {q['answer']}", '',f"**Accept:** {'; '.join(q['acceptedAnswers'])}.",f"**Hint:** {q['hint']}",f"**Source page:** {q['sourceUrl']}",f"**Direct GIF:** {q['mediaUrl']}",f"**Local filename:** `{q['localPath']}`",f"**URL evidence:** {q['mediaUrlMethod']}.",f"**Review:** {q['reviewNote'] or 'Watch the entire loop and check captions, motion, answer and workplace suitability.'}",'']
(ROOT/'ANSWER_KEY.md').write_text('\n'.join(lines)+'\n')
print('Validated 40 questions; rebuilt questions.js and ANSWER_KEY.md.')
